services:
  db:
    image: mysql:8.4
    container_name: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    restart: always

  app:
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASS: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
