services:
  db:
    image: mysql:8.4
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 10

  app:
    container_name: flask-app
    build: .
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:5000"
    environment:
      DB_DRIVER: mysql
      DB_USER: dbuser
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
